{"text": "2023-10-27 21:54:36 | INFO    | __main__:stash:129 | run - {'image': '20231026', 'role': 'EpicPlayer', 'headless': True, 'self_supervised': True}\n", "record": {"elapsed": {"repr": "0:00:01.311134", "seconds": 1.311134}, "exception": null, "extra": {"image": "20231026", "role": "EpicPlayer", "headless": true, "self_supervised": true}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "stash", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 129, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:54:36.520759+08:00", "timestamp": 1698414876.520759}}}
{"text": "2023-10-27 21:54:48 | INFO    | __main__:claim_epic_games:95 | Try to flush cookie - {'task': 'claim_epic_games'}\n", "record": {"elapsed": {"repr": "0:00:13.280550", "seconds": 13.28055}, "exception": null, "extra": {"task": "claim_epic_games"}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "claim_epic_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 95, "message": "Try to flush cookie", "module": "claim", "name": "__main__", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:54:48.490175+08:00", "timestamp": 1698414888.490175}}}
{"text": "2023-10-27 21:54:52 | SUCCESS    | epic_games.agent:_login:203 | login - {'result': 'Successfully refreshed tokens'}\n", "record": {"elapsed": {"repr": "0:00:16.956693", "seconds": 16.956693}, "exception": null, "extra": {"result": "Successfully refreshed tokens"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py"}, "function": "_login", "level": {"icon": "‚úÖ", "name": "SUCCESS", "no": 25}, "line": 203, "message": "login", "module": "agent", "name": "epic_games.agent", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:54:52.166318+08:00", "timestamp": 1698414892.166318}}}
{"text": "2023-10-27 21:54:57 | SUCCESS    | epic_games.agent:flush_token:224 | flush_token - {'path': PosixPath('/home/runner/work/epic_/epic_/epic/user_data_dir/epic-games@646129678/ctx_cookie.json')}\n", "record": {"elapsed": {"repr": "0:00:22.637311", "seconds": 22.637311}, "exception": null, "extra": {"path": "/home/runner/work/epic_/epic_/epic/user_data_dir/epic-games@646129678/ctx_cookie.json"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py"}, "function": "flush_token", "level": {"icon": "‚úÖ", "name": "SUCCESS", "no": 25}, "line": 224, "message": "flush_token", "module": "agent", "name": "epic_games.agent", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:54:57.846936+08:00", "timestamp": 1698414897.846936}}}
{"text": "2023-10-27 21:54:58 | WARNING    | epic_games.agent:get_order_history:389 | Failed to get order history, cookie may have expired - {}\n", "record": {"elapsed": {"repr": "0:00:23.032116", "seconds": 23.032116}, "exception": null, "extra": {}, "file": {"name": "agent.py", "path": "/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py"}, "function": "get_order_history", "level": {"icon": "‚ö†Ô∏è", "name": "WARNING", "no": 30}, "line": 389, "message": "Failed to get order history, cookie may have expired", "module": "agent", "name": "epic_games.agent", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:54:58.241741+08:00", "timestamp": 1698414898.241741}}}
{"text": "2023-10-27 21:54:58 | DEBUG    | __main__:create_tasks:64 | Put task - {'title': 'The Evil Within 2', 'url': 'https://store.epicgames.com/en-US/p/the-evil-within-2'}\n", "record": {"elapsed": {"repr": "0:00:23.594338", "seconds": 23.594338}, "exception": null, "extra": {"title": "The Evil Within 2", "url": "https://store.epicgames.com/en-US/p/the-evil-within-2"}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 64, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:54:58.803963+08:00", "timestamp": 1698414898.803963}}}
{"text": "2023-10-27 21:54:58 | INFO    | epic_games.agent:claim_weekly_games:232 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/the-evil-within-2'}\n", "record": {"elapsed": {"repr": "0:00:23.597778", "seconds": 23.597778}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/the-evil-within-2"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 232, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:54:58.807403+08:00", "timestamp": 1698414898.807403}}}
{"text": "2023-10-27 21:55:12 | ERROR    | __main__:run:155 | An error has been caught in function 'run', process 'MainProcess' (3587), thread 'MainThread' (139987517676416): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 159, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 155, in run\n    await agent.stash()\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 148, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 120, in claim_epic_games\n    await epic.claim_weekly_games(page, single_promotions)\n  File \"/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py\", line 248, in claim_weekly_games\n    await expect(cta_btn).to_have_text(\"View In Cart\")\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 20080, in to_have_text\n    await self._impl_obj.to_have_text(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py\", line 455, in to_have_text\n    await self._expect_impl(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py\", line 70, in _expect_impl\n    raise AssertionError(f\"{out_message}\\nActual value: {actual} {log}\")\nAssertionError: Locator expected to have text 'View In Cart'\nActual value: None \nCall log:\nLocatorAssertions.to_have_text with timeout 5000ms\nwaiting for locator(\"xpath=//aside//button[@data-testid='add-to-cart-cta-button']\")\n", "record": {"elapsed": {"repr": "0:00:37.179974", "seconds": 37.179974}, "exception": {"type": "AssertionError", "value": "Locator expected to have text 'View In Cart'\nActual value: None \nCall log:\nLocatorAssertions.to_have_text with timeout 5000ms\nwaiting for locator(\"xpath=//aside//button[@data-testid='add-to-cart-cta-button']\")", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "run", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 155, "message": "An error has been caught in function 'run', process 'MainProcess' (3587), thread 'MainThread' (139987517676416):", "module": "claim", "name": "__main__", "process": {"id": 3587, "name": "MainProcess"}, "thread": {"id": 139987517676416, "name": "MainThread"}, "time": {"repr": "2023-10-27 21:55:12.389599+08:00", "timestamp": 1698414912.389599}}}
